export const API_ERROR_CODES = {
  UNAUTHORIZED: "UNAUTHORIZED",
  FORBIDDEN: "FORBIDDEN",
  VALIDATION_ERROR: "VALIDATION_ERROR",
  NOT_FOUND: "NOT_FOUND",
  SERVICE_ZONE_UNAVAILABLE: "SERVICE_ZONE_UNAVAILABLE",
  VENDOR_CLOSED: "VENDOR_CLOSED",
  PRODUCT_UNAVAILABLE: "PRODUCT_UNAVAILABLE",
  PRICE_STALE: "PRICE_STALE",
  ORDER_STATE_INVALID: "ORDER_STATE_INVALID",
  PAYMENT_RECONCILIATION_REQUIRED: "PAYMENT_RECONCILIATION_REQUIRED",
  DUPLICATE_REQUEST: "DUPLICATE_REQUEST",
  RATE_LIMITED: "RATE_LIMITED",
  INTERNAL_ERROR: "INTERNAL_ERROR"
} as const;

export const CRITICAL_IDEMPOTENT_ACTIONS = [
  "CREATE_ORDER",
  "CANCEL_ORDER",
  "ACCEPT_ORDER",
  "REJECT_ORDER",
  "ASSIGN_RIDER",
  "MARK_DELIVERED",
  "MARK_PAYMENT_COLLECTED",
  "RECONCILE_PAYMENT",
  "APPROVE_PAYOUT"
] as const;

export const MVP_EXCLUDED_FEATURES = [
  "railway_train_food",
  "online_payment_gateway",
  "wallet",
  "subscription",
  "loyalty",
  "referral",
  "auto_dispatch",
  "live_rider_tracking",
  "multi_vendor_cart",
  "ios_public_launch"
] as const;

